### ISSUE TITLE
character encoding 'US-ASCII' causing issues in CI

### ISSUE THREAD

**Issue by tijcolem** [NREL/openstudio-extension-gem#12]
An issue with Jenkins CI jobs running the command below. It appears related to the character encoding 'US-ASCII' which should probably be UTF-8.  Need to investigate if this is being set within the container that is running in CI or explicitly being set in the code.  

This issue can be assigned to me @tijcolem 

```console
bundle exec rake openstudio:update_measures
Adding license file to measures
Initializing runner with dirname: '/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11'
config exists
Gemfile.lock exists
needs_config = false
needs_platform = false
needs_update = false
Adding measure licenses
License file path: /home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/doc_templates/LICENSE.md
Adding README.md.erb to measures where it and README.md do not exist.
Only files that have actually been changed will be listed.
Initializing runner with dirname: '/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11'
config exists
Gemfile.lock exists
needs_config = false
needs_platform = false
needs_update = false
Adding measure readmes
Readme file path: /home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/doc_templates/README.md.erb
Copying resource files from the core library to individual measures
Initializing runner with dirname: '/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11'
config exists
Gemfile.lock exists
needs_config = false
needs_platform = false
needs_update = false
Copying measure resources
Copying updated resource files from extension core directory to individual measures.
Only files that have actually been changed will be listed.
Updating COPYRIGHT in files
Initializing runner with dirname: '/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11'
rake aborted!
ArgumentError: invalid byte sequence in US-ASCII
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/runner.rb:528:in `=~'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/runner.rb:528:in `block (2 levels) in update_copyright'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/runner.rb:525:in `each'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/runner.rb:525:in `block in update_copyright'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/runner.rb:524:in `each'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/runner.rb:524:in `update_copyright'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/lib/openstudio/extension/rake_task.rb:133:in `block (2 levels) in setup_subtasks'
/home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/.bundle/install/ruby/2.2.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => openstudio:update_measures => openstudio:update_copyright
(See full trace by running task with --trace)
config exists
Gemfile.lock exists
needs_config = false
needs_platform = false
needs_update = false
Copyright file path: /home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/doc_templates/copyright_ruby.txt
Copyright file path: /home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/doc_templates/copyright_erb.txt
Copyright file path: /home/ubuntu/jenkins/workspace/openstudio-extension-gem_PR-11/doc_templates/copyright_js.txt
Encoding.default_external = US-ASCII
Encoding.default_internal = 
```

**Comment by macumber** [comment]
When using the CLI, we set the default external encoding using rb_enc_set_default_external:https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/cli/main.cpp#L501

**Comment by macumber** [comment]
From what I have read, the default encoding in Ruby 2.0 and above is UTF-8.  So I think that something must be overriding this in cases where we see problems.  Either an environment variable, magic comments in the file, or something else.

https://medium.com/rubycademy/evolution-of-ruby-string-from-1-8-to-2-5-d47afd3505df

**Comment by tijcolem** [comment]
I believe ASCII is set as default in the openstudio docker container which is causing this issue. I explicitly set UTF-8 which overrides the default charset and now the CI runs work. Ideally, this should be set during the openstudio container build process. I will open up an issue with docker openstudio to request this change. For now, setting it within the CI pipeline is works fine and is a minimal change.

Closing this issue.
