### ISSUE TITLE
OS 3.4 issue with space type wizard for some building types

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-extension-gem#149]
See issue in model articulation repo
https://github.com/NREL/openstudio-model-articulation-gem/issues/104

**Comment by DavidGoldwasser** [comment]
In making test for this in extension gem, I found an unrelated failure when using an empty model and 2004 as template where I get divided by zero error. 

This doesn't happen with 2007 or 2013

  1) Bar Methods bar_from_empty wizard_test_retail_standalone runs
     Failure/Error: bldg_def_const_set = standard.model_add_construction_set(model, climate_zone, lookup_building_type, nil, is_residential)
     
     ZeroDivisionError:
       divided by 0
     # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb:2725:in `/'
     # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb:2725:in `model_get_window_area_info'
     # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/ashrae_90_1_2004.Model.rb:17:in `model_get_percent_of_surface_range'
     # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/Standards.Model.rb:2527:in `model_find_and_add_construction'
     # ./.bundle/install/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/Standards.Model.rb:2708:in `model_add_construction_set'
     # ./lib/openstudio/extension/core/os_lib_model_generation.rb:3489:in `wizard'
     # ./spec/openstudio/core/os_lib_model_generation_spec.rb:1262:in `run'
     # ./spec/openstudio/core/os_lib_model_generation_spec.rb:1274:in `block (3 levels) in <top (required)>'
